:PROPERTIES:
:ID:       2FC9883E-274C-45E2-B750-1B94D965C0EE
:mtime:    20250915203647
:ctime:    20250915203647
:END:
#+title: 2025-09-15
A meanful day which I woke up at 5:30 and work until now!

My first day that I went to the gym at 7am, and done my workout at 9:00 am which I felt energetic for the whole day. I did saw Sarah in the first floor, and I mentioned to her that I have saw her in today's Talkshop.

I met another group member at the kitchen, we talked a little bit about the project, she also felt overwhlmed about the current project. Yes, the project is quite ambitious. And we both agreed to narrow it down.

The [[id:9089833D-3F5D-4354-9461-070A81C97F93][PSYC 5470 Current Topics in Developmental Psychology TRANSCEND Proseminar TODO]] is more productive than the previous serveral classes. and I can feel there are nuance change of the class, for example, we are suggested to
stay in the class to have a face-to-face disccusion.

It is also a little bit awkward for me, since I wrote the email to the TA to explain the challege I face and express I am thinking to change to another group.

Finally I gave up this idea, it seems the group dynamic changed a lot since another student take the leadership position which is more friendly and caring.

I am afraid that our group will back into the previous form, since I have the same experious that my previous advisor promised she would make a change, and finally she broke her promise.

No matter what, learn the fancy/fucking cognitive science.





Today was a meaningful day — I woke up at 5:30 AM and have been working ever since!

It was my first time going to the gym at 7:00 AM. I finished my workout by 9:00 AM, and I felt energized for the rest of the day. I saw Sarah on the first floor and mentioned that I had seen her in today’s Talkshop session.

Later, I ran into another group member in the kitchen. We chatted briefly about the project. She also felt overwhelmed by its current scope. Yes — it’s definitely ambitious. We both agreed that we should narrow it down.

Today's [[id:9089833D-3F5D-4354-9461-070A81C97F93][PSYC 5470 Current Topics in Developmental Psychology TRANSCEND Proseminar TODO]] felt more productive than the past several sessions. I can sense some subtle changes in the class dynamic. For example, we're now encouraged to stay after class for face-to-face discussions, which is a shift from before.

That said, things were also a little awkward for me today. I had previously emailed the TA to explain the challenges I was facing and to say I was considering switching groups.

In the end, I’ve decided not to switch. The group dynamic seems to be improving—especially since another student has stepped up to take on a leadership role. She is more friendly and caring, which makes a big difference.

Still, I can’t help but worry that things might return to how they were before. I’ve had a similar experience in the past, where my advisor promised changes that never came. That left a lasting impression.

Regardless of what happens, I’ll keep learning this fancy (and sometimes frustrating) field of cognitive science.
