:PROPERTIES:
:ID:       BE81117E-74FB-4F37-B38D-5F6DA1C7B1C2
:mtime:    20250906230430 20250904222859 20250903230132
:ctime:    20250903230132
:END:
#+title: 2025-09-03

Today I had a functional MRI scan. When I entered the machine, I felt like an astronaut inside a starship, about to launch into space.
The space was so narrow that I couldn’t even stretch out my arms. Being in such a confined area made me feel scared. It also made me think about how, after death, people are placed in coffins—an image that frightened me even more. I really hope I won’t ever have to be confined like that.

I met Sophia at the Involvement Fair today. We hadn’t seen each other in over eight months.

The most enjoyable moment today was meeting with my first mentee, Mark, who is from Vietnam. We talked for about an hour and then went to the gym to use the stair climber.
* Phd journey
I often feel stressed that my progress isn’t enough to justify a weekly meeting. Today, I ran into my advisor by chance and told him I wanted to cancel tomorrow’s meeting. In the end, I realized that was a terrible
decision—because I actually do have things to share.

One important tip I’ve learned is to write down everything about my research, no matter how small it seems.
