:PROPERTIES:
:ID:       2B30A312-6725-40CB-BB10-09DA0EA0FEF9
:mtime:    20250917214755
:ctime:    20250917214755
:END:
#+title: 2025-09-17
I did the in-personal testing at noon, and have a great chat with the experimenter. She is mother of a disablitiy child, who can not attend school in Switrzland. That's why she move to US.

Another big thing today is that when I random look at the Phd program, I find that CMU provide a Computer Science With Neural Basis of Cognition Certificate, that is design for me! I really excited about that I can be one of the student
of the CMU. Work hard!






I completed the in-person testing at noon and had a great conversation with the experimenter. She shared that she’s the mother of a child with a disability who wasn’t able to attend school in Switzerland. That’s why she decided to
move to the U.S.

Another big thing today: while randomly looking through PhD programs, I discovered that CMU offers a Computer Science PhD with a Neural Basis of Cognition Certificate — it feels like it was designed just for me! I'm really excited about the possibility of becoming a CMU student one day.

Time to work hard and make it happen!
